# Welcome to the Bird Probability Project

In [29]:
import pandas as pd
import numpy as np
import datetime

In [22]:
# data = pd.read_csv('ebd_US-CO_202001_202312_smp_relMar-2024/ebd_US-CO_202001_202312_smp_relMar-2024.txt', sep = '\t')
# data = data[['COMMON NAME', 'COUNTY', 'COUNTY CODE', 'LATITUDE', 'LONGITUDE', 'OBSERVATION DATE', 'NUMBER OBSERVERS']]
# data.to_csv('bird_data.csv')

data = pd.read_csv('bird_data.csv')

data.head(5)

,Unnamed: 0,COMMON NAME,COUNTY,COUNTY CODE,LATITUDE,LONGITUDE,OBSERVATION DATE,NUMBER OBSERVERS
0,0,Accipiter sp.,Adams,US-CO-001,39.947339,-104.747209,2020-01-10,1.0
1,1,American Crow,Adams,US-CO-001,39.797274,-104.931060,2020-01-01,5.0
2,2,American Crow,Adams,US-CO-001,39.789034,-104.905840,2020-01-02,1.0
3,3,American Crow,Adams,US-CO-001,39.830492,-104.948991,2020-01-01,10.0
4,4,American Crow,Adams,US-CO-001,39.830492,-104.948991,2020-01-01,10.0

In [77]:
counties = data['COUNTY'].unique()
birds = data['COMMON NAME'].unique()

rawDate = datetime.datetime.now()

month = rawDate.month
day = rawDate.day


def getBirds(day, month, plus_or_minus):
    """
    returns a data frame of birds that have been observed from various years during the same day and month
    plus_or_minus so many days.
    
    """
    def distance(date, target):
        '''
        Helper function
        returns the number of days away the date is from the target
        '''
        givenMonth = int(date[5:7])
        targetMonth = int(target[5:7])
        givenDay = int(date[8:])
        targetDay = int(target[8:])
        
        total = abs(givenMonth - targetMonth)*30 #grab the difference in months
        
        if givenMonth > targetMonth:
            total = total - targetDay + givenDay
        elif givenMonth < targetMonth:
            total = total - givenDay + targetDay
        else: 
            total = abs(givenDay - targetDay)
        
        return total
        
     
    if month > 10:
        target = 'xxxx-{}-{}'.format(month,day) if day > 10 else 'xxxx-{}-0{}'.format(month,day)
    else:
        target = 'xxxx-0{}-{}'.format(month,day) if day > 10 else 'xxxx-0{}-0{}'.format(month,day)
        

    # This is not the best implementation, I am just lazy and didn't want to search for the right one (help if you can)
    mask = pd.Series([distance(date, target) <= plus_or_minus for date in data['OBSERVATION DATE']])
        
    return data[mask]

In [78]:
seasonal_birds_within_20_days = getBirds(day,month, 10)

unique_birds_in_season = seasonal_birds_within_20_days['COMMON NAME'].unique()

seasonal_birds_within_20_days

,Unnamed: 0,COMMON NAME,COUNTY,COUNTY CODE,LATITUDE,LONGITUDE,OBSERVATION DATE,NUMBER OBSERVERS
444775,444775,American Avocet,Adams,US-CO-001,39.805213,-104.858449,2020-04-15,1.0
444776,444776,American Avocet,Adams,US-CO-001,39.796686,-105.034984,2020-04-19,1.0
444777,444777,American Avocet,Adams,US-CO-001,39.872580,-104.912479,2020-04-19,1.0
444778,444778,American Avocet,Adams,US-CO-001,39.808569,-104.894651,2020-04-19,1.0
444779,444779,American Avocet,Adams,US-CO-001,39.816827,-104.872647,2020-04-21,1.0
...,...,...,...,...,...,...,...,...
10931778,10931778,Least Flycatcher,Yuma,US-CO-125,40.122519,-102.708092,2023-05-02,1.0
10931791,10931791,Least Sandpiper,Yuma,US-CO-125,40.122519,-102.708092,2023-05-02,1.0
10932482,10932482,Semipalmated Plover,Yuma,US-CO-125,40.122519,-102.708092,2023-05-02,1.0
10932506,10932506,Spotted Sandpiper,Yuma,US-CO-125,40.122519,-102.708092,2023-05-03,1.0
10932557,10932557,Stilt Sandpiper,Yuma,US-CO-125,40.122519,-102.708092,2023-05-02,1.0